name: Test build

# Triggers on pushing to 'main' and 'develop'.
on:
  push:
    branches-ignore:
      - main
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: gh-pages
      MAIN_BRANCH: main
      DEVELOP_BRANCH: develop

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # https://github.com/actions/checkout#readme
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "12.x"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-packages-

      - run: yarn

      - name: Build
        run: yarn build