name: Publish docs to GitHub Pages

# Triggers on pushes to branches and tags, as well a deleting a branch.
on:
  push:
    branches:
      - main
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: gh-pages
      MAIN_BRANCH: main
      DEVELOP_BRANCH: develop

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # https://github.com/actions/checkout#readme
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

#      - run: echo $GITHUB_WORKSPACE
#      - run: ls -lah $GITHUB_WORKSPACE

      # https://github.com/actions/checkout#readme
      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      # Remove the '.git' directory in 'gh-pages' to prevent
      # any git pushing weirdness later.
      - run: rm -rf $GITHUB_WORKSPACE/gh-pages/.git
#      - run: ls -lah $GITHUB_WORKSPACE/gh-pages

      - name: Get the version
        id: get_version
        run: echo ::set-env name=BRANCH::${GITHUB_REF#refs/*/}

      - name: Setup node
        uses: actions/setup-node@v2.1.0
        with:
          node-version: "12.x"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-packages-

      - run: yarn
      # Check to make sure that docs built into www.
#      - run: ls -lah $GITHUB_WORKSPACE/www

      # Debugging messages.
#      - run: echo "${{ github.ref }}"
#      - run: echo "${{ env.MAIN_BRANCH }}"
#      - run: echo "Main check - ${{ github.ref == format('refs/heads/{0}', env.MAIN_BRANCH) }}"
#      - run: echo "Branch check - ${{ contains(github.ref, 'refs/heads/') && github.ref != format('refs/heads/{0}', env.MAIN_BRANCH) }}"
#      - run: echo "Tags check - ${{ startsWith(github.ref, 'refs/tags/') }}"

      # Only one of the following 3 steps should run.

      # If main branch:
      #   - Remove existing 'latest' directory, if it exists.
      #   - Move build into 'latest' directory.
      - name: Main branch preparations
        if: github.ref == format('refs/heads/{0}', env.MAIN_BRANCH)
        run: |
          yarn build --base=/
          cp -a $GITHUB_WORKSPACE/dist/* $GITHUB_WORKSPACE/gh-pages

      # If develop branch:
      #   - Remove existing 'latest' directory, if it exists.
      #   - Move build into 'latest' directory.
      - name: Develop branch preparations
        if: github.ref == format('refs/heads/{0}', env.DEVELOP_BRANCH)
        run: |
          yarn build --base=/latest/
          rm -rf $GITHUB_WORKSPACE/gh-pages/latest
          mv $GITHUB_WORKSPACE/dist $GITHUB_WORKSPACE/gh-pages/latest

      # Look at the 'gh-pages' directory to see if everything looks right.
#      - run: ls -lah $GITHUB_WORKSPACE/gh-pages

      # https://github.com/JamesIves/github-pages-deploy-action#readme
      - name: Deploy docs 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ env.TARGET_BRANCH }} # The branch the action should deploy to.
          FOLDER: gh-pages # The folder the action should deploy.

